### ISSUE TITLE
Result file of the suite not written when test are not passing - Failed to execute goal nl.sijpesteijn.testing.fitnesse.plugins instead

### ISSUE THREAD

**Issue by thomas-romuald** [sijpesteijn/mafia-maven-plugin#28]
Hi, when a suite finish with some errors and exceptions:
````
[INFO] FitNesse start on: http://localhost:9090
[INFO] Starting test run....
[INFO] SaIntegrationTest failed with wrong exception.
[INFO] Test: SaIntegrationTest(39 right, 34 wrong, 5 ignored, 33 exceptions, file: 20160707172042_39_34_5_33.xml)
[INFO] Finished test run.
````

The build finish with this error, and the xml result file of the whole suite are not written. The file 20160707172042_39_34_5_33.xml is not there.

````
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:19 min
[INFO] Finished at: 2016-07-07T17:20:42+01:00
[INFO] Final Memory: 38M/310M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal nl.sijpesteijn.testing.fitnesse.plugins:mafia-maven-plugin:2.1.11:test (run-fitnesse-tests) on project integration-fitnesse-fixtures: Test run interrupted by stop conditions. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal nl.sijpesteijn.testing.fitnesse.plugins:mafia-maven-plugin:2.1.11:test (run-fitnesse-tests) on project integration-fitnesse-fixtures: Test run interrupted by stop conditions.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Test run interrupted by stop conditions.
	at nl.sijpesteijn.testing.fitnesse.plugins.FitNesseRunnerMojo.execute(FitNesseRunnerMojo.java:239)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR] 
````

We can avoid that with:
````
<stopTestsOnException>false</stopTestsOnException>
<stopTestsOnWrong>false</stopTestsOnWrong>
````
In this case the we got the xml result of the full test suite but the build appears SUCCESS.

Is it possible to get the full result even if some issues appear during the test and end with FAILURE to show that the tests didn't pass but avoid this ambiguous message  [ERROR] Failed to execute goal nl.sijpesteijn.testing.fitnesse.plugins:mafia-maven-plugin ?

**Comment by thomas-romuald** [comment]
bad comment, I closed it.
